---

services:

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   hostname: certbot
  #   volumes:
  #     - ./data/ssl:/etc/letsencrypt
  #   ports:
  #     - 80:80
  #   command: certonly --non-interactive --keep-until-expiring --standalone --preferred-challenges http --agree-tos --email mail@example.com -d example.com

  openconnect:
    # depends_on:
    #   certbot:
    #     condition: service_completed_successfully
    image: r4venme/openconnect:v1.3-sid
    container_name: openconnect
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
    cap_add:
      - NET_ADMIN
    hostname: openconnect
    #env_file:
      #- .env
    environment:
      - "TZ=Europe/Moscow"
      - "SRV_CN=example.com"
      - "SRV_CA=Example CA"
      #- OTP_ENABLE="true"
      #- OTP_SEND_BY_EMAIL="true"
      #- MSMTP_HOST="smtp.example.com"
      #- MSMTP_PORT="465"
      #- MSMTP_USER="mail@example.com"
      #- MSMTP_PASSWORD="SuPeRsEcReTpAsSwOrD"
      #- MSMTP_FROM="mail@example.com"
      #- OTP_SEND_BY_TELEGRAM="true"
      #- TG_TOKEN="1234567890:QWERTYuio-PA1DFGHJ2_KlzxcVBNmqWEr3t"
    volumes:
      - ./data:/etc/ocserv
      #- /etc/passwd:/etc/passwd:ro
      #- /etc/group:/etc/group:ro
      #- /etc/shadow:/etc/shadow:ro
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 43443:443/tcp
